server:
  port: 8081
spring:
  application:
    name: serviceA
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
  ddatasource:
    url: ${DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000u
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG
