server:
  port: 8081
spring:
  application:
    name: serviceA
  datasource:
    url: jdbc:postgresql://dpg-cuojhk1opnds738t2uh0-a:5432/servicea
    username: servicea
    password: yFryoakYuREGH6RcaL9bXMNgj8KbwfGx
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update  # Bisa diganti "validate" atau "none" di production
      show-sql: true  # Menampilkan SQL query di log
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000u
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG
