server:
  port: 8080
spring:
  application:
    name: serviceA
  datasource:
    url: jdbc:postgresql://34.101.139.132:5432/postgres
    username: postgres
    password: 50~apjlxgqp2X_~y
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000u
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG
booking-service:
  url: https://serviceb-338365327766.asia-southeast2.run.app
